local Wave1 = table.freeze({

	[1] = {
		AmountBase = 1,
		AmountTank = 0,
		AmountFast = 0,
		AmountElite = 0,
		AmountPlus = 0,
		MoneyReward = 10,
	},
	[2] = {
		AmountBase = 2,
		AmountTank = 0,
		AmountFast = 0,
		AmountElite = 0,
		AmountPlus = 0,
		MoneyReward = 20,
	},
	[3] = {
		AmountBase = 2,
		AmountTank = 0,
		AmountFast = 1,
		AmountElite = 0,
		AmountPlus = 0,
		MoneyReward = 35,
	},
	[4] = {
		AmountBase = 3,
		AmountTank = 0,
		AmountFast = 1,
		AmountElite = 0,
		AmountPlus = 0,
		MoneyReward = 45,
	},
	[5] = {
		AmountBase = 3,
		AmountTank = 0,
		AmountFast = 2,
		AmountElite = 0,
		AmountPlus = 0,
		MoneyReward = 60,
	},
	[6] = {
		AmountBase = 4,
		AmountTank = 0,
		AmountFast = 2,
		AmountElite = 0,
		AmountPlus = 0,
		MoneyReward = 70,
	},
	[7] = {
		AmountBase = 4,
		AmountTank = 0,
		AmountFast = 3,
		AmountElite = 0,
		AmountPlus = 0,
		MoneyReward = 85,
	},
	[8] = {
		AmountBase = 5,
		AmountTank = 0,
		AmountFast = 3,
		AmountElite = 0,
		AmountPlus = 0,
		MoneyReward = 95,
	},
	[9] = {
		AmountBase = 6,
		AmountTank = 0,
		AmountFast = 2,
		AmountElite = 0,
		AmountPlus = 0,
		MoneyReward = 90,
	},
	[10] = {
		AmountBase = 5,
		AmountTank = 1,
		AmountFast = 2,
		AmountElite = 0,
		AmountPlus = 0,
		MoneyReward = 105,
	},
	[11] = {
		AmountBase = 4,
		AmountTank = 2,
		AmountFast = 2,
		AmountElite = 0,
		AmountPlus = 0,
		MoneyReward = 120,
	},
	[12] = {
		AmountBase = 3,
		AmountTank = 3,
		AmountFast = 2,
		AmountElite = 0,
		AmountPlus = 0,
		MoneyReward = 135,
	},
	[13] = {
		AmountBase = 2,
		AmountTank = 4,
		AmountFast = 2,
		AmountElite = 0,
		AmountPlus = 0,
		MoneyReward = 150,
	},
	[14] = {
		AmountBase = 1,
		AmountTank = 5,
		AmountFast = 2,
		AmountElite = 0,
		AmountPlus = 0,
		MoneyReward = 165,
	},
	[15] = {
		AmountBase = 0,
		AmountTank = 6,
		AmountFast = 2,
		AmountElite = 0,
		AmountPlus = 0,
		MoneyReward = 180,
	},
	[16] = {
		AmountBase = 1,
		AmountTank = 6,
		AmountFast = 1,
		AmountElite = 0,
		AmountPlus = 0,
		MoneyReward = 190,
	},
	[17] = {
		AmountBase = 2,
		AmountTank = 6,
		AmountFast = 0,
		AmountElite = 0,
		AmountPlus = 0,
		MoneyReward = 200,
	},
	[18] = {
		AmountBase = 3,
		AmountTank = 5,
		AmountFast = 0,
		AmountElite = 0,
		AmountPlus = 0,
		MoneyReward = 230,
	},
	[19] = {
		AmountBase = 4,
		AmountTank = 4,
		AmountFast = 0,
		AmountElite = 0,
		AmountPlus = 0,
		MoneyReward = 240,
	},
	[20] = {
		AmountBase = 5,
		AmountTank = 3,
		AmountFast = 0,
		AmountElite = 0,
		AmountPlus = 0,
		MoneyReward = 250,
	},
	[21] = {
		AmountBase = 6,
		AmountTank = 2,
		AmountFast = 0,
		AmountElite = 0,
		AmountPlus = 0,
		MoneyReward = 260,
	},
	[22] = {
		AmountBase = 7,
		AmountTank = 1,
		AmountFast = 0,
		AmountElite = 0,
		AmountPlus = 0,
		MoneyReward = 270,
	},
	[23] = {
		AmountBase = 8,
		AmountTank = 0,
		AmountFast = 0,
		AmountElite = 0,
		AmountPlus = 0,
		MoneyReward = 280,
	},
	[24] = {
		AmountBase = 7,
		AmountTank = 1,
		AmountFast = 0,
		AmountElite = 0,
		AmountPlus = 0,
		MoneyReward = 205,
	},
	[25] = {},
})

return Wave1
