local Tags = table.freeze({
	-- Base Shop Screen:
	BASE_SHOP_BLOCKS_CONTAINER = "BASE_SHOP_BLOCKS_CONTAINER",
	BASE_SHOP_BLOCKS_TAB_BUTTON = "BASE_SHOP_BLOCKS_TAB_BUTTON",
	BASE_SHOP_CLOSE_BUTTON = "BASE_SHOP_CLOSE_BUTTON",
	BASE_SHOP_MELEE_CONTAINER = "BASE_SHOP_MELEE_CONTAINER",
	BASE_SHOP_MELEE_TAB_BUTTON = "BASE_SHOP_MELEE_TAB_BUTTON",
	BASE_SHOP_RANGED_CONTAINER = "BASE_SHOP_RANGED_CONTAINER",
	BASE_SHOP_RANGED_TAB_BUTTON = "BASE_SHOP_RANGED_TAB_BUTTON",
	BASE_SHOP_RESTOCK_ALL_BUTTON = "BASE_SHOP_RESTOCK_ALL_BUTTON",
	BASE_SHOP_SCREEN = "BASE_SHOP_SCREEN",
	BASE_SHOP_TIME_TEXT = "BASE_SHOP_TIME_TEXT",
	-- Eggs and Crates Screen:
	EGGS_AND_CRATES_SCREEN = "EGGS_AND_CRATES_SCREEN",
	-- HUD Elements:
	HUD_BUTTON_BASE = "HUD_BUTTON_BASE",
	HUD_BUTTON_FIGHT = "HUD_BUTTON_FIGHT",
	HUD_BUTTON_SHOP = "HUD_BUTTON_SHOP",
	HUD_BUTTON_STOP_FIGHT = "HUD_BUTTON_STOP_FIGHT",
	HUD_HOTBAR_BUTTON_UNITS_BACKPACK = "HUD_HOTBAR_BUTTON_UNITS_BACKPACK",
	HUD_HOTBAR_BUTTON_REMOVE_UNIT = "HUD_HOTBAR_BUTTON_REMOVE_UNIT",
	HUD_HOTBAR_BUTTON_WEAPONS_BACKPACK = "HUD_HOTBAR_BUTTON_WEAPONS_BACKPACK",
	HUD_HOTBAR_BUTTON_EGGS_AND_CRATES = "HUD_HOTBAR_BUTTON_EGGS_AND_CRATES",
	HUD_HEALTH_BAR = "HUD_HEALTH_BAR",
	HUD_HEALTH_CONTAINER = "HUD_HEALTH_CONTAINER",
	HUD_HEALTH_TEXT = "HUD_HEALTH_TEXT",
	HUD_MONEY_HISTORY = "HUD_MONEY_HISTORY",
	HUD_MONEY_TEXT = "HUD_MONEY_TEXT",
	HUD_WAVE_BAR = "HUD_WAVE_BAR",
	HUD_WAVE_CONTAINER = "HUD_WAVE_CONTAINER",
	HUD_WAVE_TEXT = "HUD_WAVE_TEXT",
	-- Units Backpack Screen:
	UNITS_BACKPACK_CLOSE_BUTTON = "UNITS_BACKPACK_CLOSE_BUTTON",
	UNITS_BACKPACK_ITEMS_CONTAINER = "UNITS_BACKPACK_ITEMS_CONTAINER",
	UNITS_BACKPACK_REMOVE_ALL_BUTTON = "UNITS_BACKPACK_REMOVE_ALL_BUTTON",
	UNITS_BACKPACK_SCREEN = "UNITS_BACKPACK_SCREEN",
	-- Weapons Backpack Screen:
	WEAPONS_BACKPACK_CLOSE_BUTTON = "WEAPONS_BACKPACK_CLOSE_BUTTON",
	WEAPONS_BACKPACK_ITEMS_CONTAINER = "WEAPONS_BACKPACK_ITEMS_CONTAINER",
	WEAPONS_BACKPACK_SCREEN = "WEAPONS_BACKPACK_SCREEN",
	-- You Died Screen:
	YOU_DIED_BUTTON_CLOSE = "YOU_DIED_BUTTON_CLOSE",
	YOU_DIED_SCREEN = "YOU_DIED_SCREEN",
})

return Tags
