local UnitType = require(script.Parent.unitType)
local Weapons = table.freeze({
	Fist = {
		Name = "Fist",
		Damage = 5,
		Range = 3,
		FireRate = 1,
		Type = UnitType.Melee,
	},
	AK47 = {
		Name = "AK47",
		Damage = 30,
		Range = 100,
		FireRate = 0.1,
		AmmoCapacity = 30,
		ReloadTime = 2,
		Type = UnitType.Ranged,
	},
	Axe = {
		Name = "Axe",
		Damage = 40,
		Range = 5,
		FireRate = 1,
		Type = UnitType.Melee,
	},
	FireAxe = {
		Name = "FireAxe",
		Damage = 50,
		Range = 5,
		FireRate = 1,
		Type = UnitType.Melee,
	},
	Hammer = {
		Name = "Hammer",
		Damage = 45,
		Range = 5,
		FireRate = 1.2,
		Type = UnitType.Melee,
	},
	KatanaBasic = {
		Name = "KatanaBasic",
		Damage = 35,
		Range = 6,
		FireRate = 0.8,
		Type = UnitType.Melee,
	},
	M16 = {
		Name = "M16",
		Damage = 28,
		Range = 120,
		FireRate = 0.12,
		AmmoCapacity = 30,
		ReloadTime = 2.5,
		Type = UnitType.Ranged,
	},
	Minigun = {
		Name = "Minigun",
		Damage = 20,
		Range = 80,
		FireRate = 0.05,
		AmmoCapacity = 200,
		ReloadTime = 5,
		Type = UnitType.Ranged,
	},
	NormalBat = {
		Name = "NormalBat",
		Damage = 25,
		Range = 5,
		FireRate = 0.9,
		Type = UnitType.Melee,
	},
	Uzi = {
		Name = "Uzi",
		Damage = 18,
		Range = 60,
		FireRate = 0.08,
		AmmoCapacity = 32,
		ReloadTime = 1.8,
		Type = UnitType.Ranged,
	},
	CappuccinoSword = {
		Name = "CappuccinoSword",
		Damage = 60,
		Range = 7,
		FireRate = 0.7,
		Type = UnitType.Melee,
	},
	ChainSaw = {
		Name = "ChainSaw",
		Damage = 15,
		Range = 4,
		FireRate = 0.15,
		Type = UnitType.Melee,
	},
	CrossbowRegular = {
		Name = "CrossbowRegular",
		Damage = 55,
		Range = 100,
		FireRate = 1.5,
		AmmoCapacity = 1,
		ReloadTime = 2,
		Type = UnitType.Ranged,
	},
	BobritoMachineGun = {
		Name = "BobritoMachineGun",
		Damage = 25,
		Range = 90,
		FireRate = 0.1,
		AmmoCapacity = 50,
		ReloadTime = 3,
		Type = UnitType.Ranged,
	},
	NoobiniCrossbow = {
		Name = "NoobiniCrossbow",
		Damage = 65,
		Range = 110,
		FireRate = 1.2,
		AmmoCapacity = 1,
		ReloadTime = 1.8,
		Type = UnitType.Ranged,
	},
	Pistol = {
		Name = "Pistol",
		Damage = 15,
		Range = 50,
		FireRate = 0.5,
		AmmoCapacity = 12,
		ReloadTime = 1.5,
		Type = UnitType.Ranged,
	},
	RocketLaucher = {
		Name = "RocketLaucher",
		Damage = 100,
		Range = 150,
		FireRate = 3,
		AmmoCapacity = 1,
		ReloadTime = 4,
		Type = UnitType.Ranged,
	},
	SahurBat = {
		Name = "SahurBat",
		Damage = 55,
		Range = 6,
		FireRate = 0.8,
		Type = UnitType.Melee,
	},
})

return Weapons
